version: '3.8'

services:
  wisper:
    build: .
    volumes:
      - ./:/app
      - ./.cache:/root/.cache
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /mnt/wslg:/mnt/wslg
      - ./.streamlit:/root/.streamlit

    environment:
      - PULSE_SERVER=/mnt/wslg/PulseServer
      - DISPLAY=$DISPLAY
      # - PULSE_SERVER=$PULSE_SERVER
      - WAYLAND_DISPLAY=$WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR
    ports:
      - 8181:8181
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    working_dir: /app
    tty: true
    command: uvicorn faster_whisper_api_server:app --reload  --host=0.0.0.0 --port=8181
    # network_mode: "host"
