services:
  app:
    build: .
    volumes:
      - ./:/app
    
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    working_dir: /app
    tty: true
    # restart: unless-stopped